[package]
name = "terminal-emoji"
description = "A library for safely displaying emoji inside of terminals"
license = "Apache-2.0 OR MIT"
version = "0.1.0"
authors = ["SirWindfield <SirWindfield@users.noreply.github.com>"]
edition = "2018"

[dependencies]
crossterm = "0.19.0"
lazy_static = "1.4.0"
